"""
Initial Schema

Revision ID: b7ada8e2696e
Revises:
Create Date: 2026-04-24 11:31:31.438548

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7ada8e2696e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sharepoint_solution_docs",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("sp_id", sa.Text(), nullable=False),
        sa.Column("file_type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=True),
        sa.Column(
            "img_metadata",
            postgresql.ARRAY(sa.Text(), dimensions=1),
            nullable=True,
        ),
        sa.Column(
            "keywords",
            postgresql.ARRAY(sa.Text(), dimensions=1),
            nullable=True,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("web_url", sa.Text(), nullable=False),
        sa.Column(
            "created_datetime", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "last_modified_datetime",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sp_id"),
        schema="ba",
    )
    op.create_index(
        op.f("ix_ba_sharepoint_solution_docs_file_path"),
        "sharepoint_solution_docs",
        ["file_path"],
        unique=False,
        schema="ba",
    )
    op.create_index(
        op.f("ix_ba_sharepoint_solution_docs_id"),
        "sharepoint_solution_docs",
        ["id"],
        unique=False,
        schema="ba",
    )
    op.create_index(
        op.f("ix_ba_sharepoint_solution_docs_keywords"),
        "sharepoint_solution_docs",
        ["keywords"],
        unique=False,
        schema="ba",
    )
    op.create_index(
        op.f("ix_ba_sharepoint_solution_docs_name"),
        "sharepoint_solution_docs",
        ["name"],
        unique=False,
        schema="ba",
    )
    op.drop_index(
        op.f("ix_public_sharepoint_solution_docs_file_path"),
        table_name="sharepoint_solution_docs",
    )
    op.drop_index(
        op.f("ix_public_sharepoint_solution_docs_id"),
        table_name="sharepoint_solution_docs",
    )
    op.drop_index(
        op.f("ix_public_sharepoint_solution_docs_keywords"),
        table_name="sharepoint_solution_docs",
    )
    op.drop_index(
        op.f("ix_public_sharepoint_solution_docs_name"),
        table_name="sharepoint_solution_docs",
    )
    op.drop_table("sharepoint_solution_docs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sharepoint_solution_docs",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("sp_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "content_text", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "img_metadata",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "keywords",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("web_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_modified_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_synced",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("sharepoint_solution_docs_pkey")
        ),
        sa.UniqueConstraint(
            "sp_id",
            name=op.f("sharepoint_solution_docs_sp_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_public_sharepoint_solution_docs_name"),
        "sharepoint_solution_docs",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_public_sharepoint_solution_docs_keywords"),
        "sharepoint_solution_docs",
        ["keywords"],
        unique=False,
    )
    op.create_index(
        op.f("ix_public_sharepoint_solution_docs_id"),
        "sharepoint_solution_docs",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_public_sharepoint_solution_docs_file_path"),
        "sharepoint_solution_docs",
        ["file_path"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_ba_sharepoint_solution_docs_name"),
        table_name="sharepoint_solution_docs",
        schema="ba",
    )
    op.drop_index(
        op.f("ix_ba_sharepoint_solution_docs_keywords"),
        table_name="sharepoint_solution_docs",
        schema="ba",
    )
    op.drop_index(
        op.f("ix_ba_sharepoint_solution_docs_id"),
        table_name="sharepoint_solution_docs",
        schema="ba",
    )
    op.drop_index(
        op.f("ix_ba_sharepoint_solution_docs_file_path"),
        table_name="sharepoint_solution_docs",
        schema="ba",
    )
    op.drop_table("sharepoint_solution_docs", schema="ba")
    # ### end Alembic commands ###
